// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Run `npm run icons` to regenerate.

const techIcons = [
  {
    "name": "TypeScript",
    "imgPath": "/images/tech/typescript.svg",
    "hex": "#3178C6",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "JavaScript",
    "imgPath": "/images/tech/javascript.svg",
    "hex": "#F7DF1E",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Python",
    "imgPath": "/images/tech/python.svg",
    "hex": "#3776AB",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Node.js",
    "imgPath": "/images/tech/node-js.svg",
    "hex": "#5FA04E",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Express",
    "imgPath": "/images/tech/express.svg",
    "hex": "#0A0A0A",
    "invertOnDark": true,
    "invertOnLight": false
  },
  {
    "name": "React",
    "imgPath": "/images/tech/react.svg",
    "hex": "#61DAFB",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Redux",
    "imgPath": "/images/tech/redux.svg",
    "hex": "#764ABC",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Next.js",
    "imgPath": "/images/tech/next-js.svg",
    "hex": "#000000",
    "invertOnDark": true,
    "invertOnLight": false
  },
  {
    "name": "PostgreSQL",
    "imgPath": "/images/tech/postgresql.svg",
    "hex": "#4169E1",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "MySQL",
    "imgPath": "/images/tech/mysql.svg",
    "hex": "#4479A1",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "MongoDB",
    "imgPath": "/images/tech/mongodb.svg",
    "hex": "#47A248",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Redis",
    "imgPath": "/images/tech/redis.svg",
    "hex": "#FF4438",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "RabbitMQ",
    "imgPath": "/images/tech/rabbitmq.svg",
    "hex": "#FF6600",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Docker",
    "imgPath": "/images/tech/docker.svg",
    "hex": "#2496ED",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Socket.IO",
    "imgPath": "/images/tech/socket-io.svg",
    "hex": "#010101",
    "invertOnDark": true,
    "invertOnLight": false
  },
  {
    "name": "Nginx",
    "imgPath": "/images/tech/nginx.svg",
    "hex": "#009639",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Git",
    "imgPath": "/images/tech/git.svg",
    "hex": "#F03C2E",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "GitHub Actions",
    "imgPath": "/images/tech/github-actions.svg",
    "hex": "#2088FF",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Linux",
    "imgPath": "/images/tech/linux.svg",
    "hex": "#FCC624",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "GitHub",
    "imgPath": "/images/tech/github.svg",
    "hex": "#181717",
    "invertOnDark": true,
    "invertOnLight": false
  },
  {
    "name": "Postman",
    "imgPath": "/images/tech/postman.svg",
    "hex": "#FF6C37",
    "invertOnDark": false,
    "invertOnLight": false
  },
  {
    "name": "Three.js",
    "imgPath": "/images/tech/three-js.svg",
    "hex": "#000000",
    "invertOnDark": true,
    "invertOnLight": false
  },
  {
    "name": "Tailwind CSS",
    "imgPath": "/images/tech/tailwind-css.svg",
    "hex": "#06B6D4",
    "invertOnDark": false,
    "invertOnLight": false
  }
];

export default techIcons;
