import * as si from "simple-icons";
import { mkdirSync, writeFileSync } from "node:fs";

const WANT = [
  ["siTypescript", "TypeScript"], ["siJavascript", "JavaScript"],
  ["siPython", "Python"], ["siNodedotjs", "Node.js"], ["siExpress", "Express"],
  ["siReact", "React"], ["siRedux", "Redux"], ["siNextdotjs", "Next.js"],
  ["siPostgresql", "PostgreSQL"], ["siMysql", "MySQL"], ["siMongodb", "MongoDB"],
  ["siRedis", "Redis"], ["siRabbitmq", "RabbitMQ"], ["siDocker", "Docker"],
  ["siSocketdotio", "Socket.IO"], ["siNginx", "Nginx"], ["siGit", "Git"],
  ["siGithubactions", "GitHub Actions"], ["siLinux", "Linux"],
  ["siGithub", "GitHub"], ["siPostman", "Postman"],
  ["siThreedotjs", "Three.js"], ["siTailwindcss", "Tailwind CSS"],
];

const luminance = (hex) => {
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
  const f = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
};

const dir = "public/images/tech";
mkdirSync(dir, { recursive: true });

const manifest = [];
const missing = [];

for (const [key, label] of WANT) {
  const icon = si[key];
  if (!icon) { missing.push(key); continue; }

  const slug = label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const hex = icon.hex;
  const lum = luminance(hex);

  writeFileSync(
    `${dir}/${slug}.svg`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#${hex}">` +
      `<title>${label}</title><path d="${icon.path}"/></svg>`
  );

  manifest.push({
    name: label,
    imgPath: `/images/tech/${slug}.svg`,
    hex: `#${hex}`,
    // Too dark to read on the dark theme; too light to read on the light one.
    invertOnDark: lum < 0.06,
    invertOnLight: lum > 0.85,
  });
}

writeFileSync(
  "constants/tech-icons.js",
  "// GENERATED by scripts/generate-icons.mjs — do not edit by hand.\n" +
    "// Run `npm run icons` to regenerate.\n\n" +
    "const techIcons = " + JSON.stringify(manifest, null, 2) + ";\n\n" +
    "export default techIcons;\n"
);

console.log(`generated ${manifest.length} brand-coloured icons in ${dir}`);
console.log(`  invert on dark:  ${manifest.filter((m) => m.invertOnDark).map((m) => m.name).join(", ") || "none"}`);
console.log(`  invert on light: ${manifest.filter((m) => m.invertOnLight).map((m) => m.name).join(", ") || "none"}`);
if (missing.length) console.warn(`not in simple-icons: ${missing.join(", ")}`);
// Note: AWS was removed from simple-icons over trademark policy — deliberately absent.
